# Generated by Django 5.2 on 2025-04-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
