# Generated by Django 5.2 on 2025-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp2', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Item_name',
            field=models.CharField(max_length=40),
        ),
    ]
