# Generated by Django 5.2 on 2025-04-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp2', '0005_rename_item_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
