# Generated by Django 5.2 on 2025-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp2', '0006_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
    ]
